### PR TITLE
add cors to production api

### PR DESCRIPTION
**Pull request by Nilegfx**
- [x] add cors to production api

### CODE REVIEW

**Comment by elharony** [comment]
Thanks, @Nilegfx!
It's merged now.

**Comment by elharony** [comment]
I noticed that it doesn't return the fonts according to the `popularity`. Can you please fix it in the backend?
It's much easier to work with the most popular fonts, instead of the `alpha` order.

What do you think, @Nilegfx ?

**Comment by Nilegfx** [comment]
sorry. I forgot that. will do it.

**Comment by elharony** [comment]
No problem @Nilegfx ,
Please commit it when you do so, and I will merge it then.

**Pull request merged**
